sensor_kit_base_link:
  camera0/camera_link:
    x: 0.015
    y: 0.0
    z: -0.805
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  # camera1/camera_link:
  #   x: 0.015
  #   y: 0.0
  #   z: -0.805
  #   roll: 0.0
  #   pitch: 0.0
  #   yaw: 0.0
  lslidar_top_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: -1.57079632679
  gnss_link:
    x: -1.7
    y: 1.48
    z: 0.35
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  smrc/imu_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  ars408/radar_link:
    x: 0.0
    y: 0.0
    z: -0.37
    roll: 0.0
    pitch: 0.0
    yaw: 0
